### ISSUE TITLE
Страница с 'Коледни подаръци' - нов дизайн и имплементация

### ISSUE THREAD

**Issue by batruji** [stefanikolov/metareading#1]
@stefanikolov @bencheva-v 

Освен прилагане на новия дизайн, желаем да има:
- хардкоднато URL на страницата - http://metareading.com/#!/articles/28 -> http://metareading.com/#!/christmas_special_offers. Добре е да има rel="canonical" към стария адрес (ще е нужно и при URL rewrite фукнционалността)
- хардкоднати og:tags -> при споделяне да се вижда правилната картинка (og:image - от дизайна изибраме или правим нова с размери 1200 x 630 или ако няма толкова голяма 600 x 315), за og:title ползваме заглавието от дизайна, за og:description - първия абзац след заглавието 'До 31ви декември ...'
- правилно изпълнени h1, h2, h3 и т.н., картинки с alt, widht и height
- уверяваме се, че страницата може да се кролва от ботове

**Comment by stefanikolov** [comment]
Страницата е дизайнната, статично са сложени FB:tags за всички пуснати страници (променливата за адрес не хвана и ще се сложи в routes.js за всеки поотделно за в бъдеще), каноникала и той ще е там.
