### ISSUE TITLE
Падащо меню - Курсове

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#14]
Моля в падащото меню Курсове, Индивидуална бизнес консултация да се преименува на "Бизнес консултация" за да заема един ред и ако може и на нея да и добавим значка: 
![recency](https://cloud.githubusercontent.com/assets/16803986/12720673/8ada0928-c904-11e5-8aac-64ec8fd93321.png)

Ако може и Творчески занимания за деца да е на един ред със значката :)
Вариант да го прекръстим, за да е малко по-кратко е Творчески занимания-деца.

**Comment by bencheva-v** [comment]
Увеличено е падащото меню с още 10%, възможно е да го гледате на по-малка резолюция и затова да падат линкове на долния ред. Ако е необходимо, ще променим и текста.

**Comment by Meta-Luna** [comment]
Не супер, така излиза перфектно :)
