### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by batruji** [stefanikolov/metareading#2]
При регистрация / логин да има опция човек да влиза с Facebook профила си.

Същия facebook application следва да се използва и за социалните споделяния, така че всичко да е на едно място.

**Comment by stefanikolov** [comment]
Last tests и днес комитвам

**Comment by batruji** [comment]
Има ли начин съществуващи потребители да добавят facebook логин към профила си? Ако не - моля да добавиш такъв. Благодаря

**Comment by stefanikolov** [comment]
Работи се по това.
Ето крайният вариант: https://atlas.mindmup.com/2015/12/f9410d9089eb0133bcfa17117fe97817/facebook_login_button/index.html

**Comment by stefanikolov** [comment]
За момента ако съществуващ потребител мине през ФБ логин, то към акаунта му се добавя неговият ФБ номер. Сега ще мисля и ръчното връзване на акаунт с ФБ (това за което говорихме).

**Comment by batruji** [comment]
Моля виж тук: https://podio.com/metareadingcom/contacts/apps/backlog/items/295

![error](https://cloud.githubusercontent.com/assets/846646/11952936/daaa2f12-a8a4-11e5-9d5a-5ede2165eb86.png)

Дали тази грешка е свързана с новата интеграция и можеш ли да потвърдиш дали е била оправена. Би трябвало в логовете да има повече инфо.

Мерси

**Comment by stefanikolov** [comment]
Потребителят е излязъл вече и затова няма ИД.

**Comment by batruji** [comment]
Супер - значи проблема ни е по-скоро в това, че вообще показваме такива грешки на потребителя - на Production не следва да се виждат подобни неща. Може би има начин показването на подобни грешки да се спре, пък ако възникват да ги препращаме към началната страница?
