### ISSUE TITLE
Профил -> Значки

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#22]
Моля преди това да се изпълни issue Профил -> Резултати :) - Мерси!

![1 2](https://cloud.githubusercontent.com/assets/16803986/12816598/f9d4b7bc-cb55-11e5-88e8-b46769391c90.png)

Променяме значките, като слагаме всичко на български и отдолу всяка значка, колко точки ни носи. Максималният достижим резултат е 905 (сбора от точките като всички значки са активирани)

Където можем да попълним информацията като кликнем върху значката ни отваря полето да попълним нужното на мястото на точките по този начин:
![akt](https://cloud.githubusercontent.com/assets/16803986/12819813/42ae1780-cb65-11e5-81e1-1ea551d5aaa9.png)
 
Или съответно ни препраща към линк за попълване на въпросник или игра.

3-те големи значки се активират, когато са активирани всички значки от различните 3 категории, или както следва:

ИНФОРМАЦИЯ (89т.) - Имейл (5т.), Име (5т.), Фамилия (5т.), Телефон (8т.), Разбрах от (8т.), Град (8т.), Рождена дата (13т.), Час на раждане (13т.), Аватар (13т.) - когато значките от този тип се активират текста е в зелено.
ПОСТИЖЕНИЯ (89т.) - скорост на четене (21т.) , възприемане (21т.) , памет (21т.) , креативност (21т.) - отношение (21т.), майерс-бригс (34т.), търг. инт. (34т.) - когато значките от този тип се активират текста е в оранжево
МИСИИ (89т.) - книга (55т.), автор (55т.), въпроси (55т.), отговори (55т.), мисловна карта (55т.), история (55т.), цел (55т.) - когато значките от този тип се активират текста е в синьо

* фейсбук значката носи 1т. и не е задължително да е активна за да се стигне до МЕТАзначката, но е включва към максималният резултат.
*МЕТА значката носи 1т. - когато всички значки са активни, това е наградата (за нея ще обесним подробно в друга задачка)

Прикачам линк с избраните картинки за всяка значка. Към повечето съм добавила и неактивната значка (ако това е улеснение), към 3,4 неактивни значки обаче не успях да намеря, ако са нужни кажете да пиша на дизайнерката. :)
https://podio.com/metareadingcom/contacts/apps/backlog/items/271

**Comment by Meta-Luna** [comment]
Супер :)

Сега като го преглеждам обаче забелязвам, че не става ясно въобще за какво иде реч :laughing: 

Нека прекръстим Значки на Постижения.
Може ли значките, които активират значката Информация + значката Информация да си останат зелени / значките, които активират Постижения + зн. Постижения да са оранжеви / и съответно Мисии - сини.

Добавят се +186 точки (1091 общо) към общият резултат от добавените значки Мотивация, Карти, Метачетене и Метабизнес (остават все още неактивни значки, ще опиша за тях в отделни задачи)

Трите значки си остаат по същият начин, супер са като големина :)

Изображението в Мета значката е аватара, а под Мета значката се слага полето с точките.

Най-отгоре се добавя поле с пояснение.

![znachki](https://cloud.githubusercontent.com/assets/16803986/14984913/d16e784c-114d-11e6-9806-d44648b9c463.jpg)

**Comment by bencheva-v** [comment]
Тази мета значка как се активира и като се активира какво се случва или това ще се опише отделно?

**Comment by Meta-Luna** [comment]
Оп да, забравила съм за баджа, извинявай.

Относно размера, по-малко може и да е по-хубаво :)

За Мета значката ще разпиша направо отделно, защото още не сме го изкоментирали финално, как да е. 

![378](https://cloud.githubusercontent.com/assets/16803986/15110803/b35f60c6-15eb-11e6-9f25-e4a1e8030ccd.png)


![leader](https://cloud.githubusercontent.com/assets/16803986/15110813/c613f948-15eb-11e6-9257-455c12e6345c.png)
