### ISSUE TITLE
Профил -> Информация

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#24]
Променяме Информацията в профила като дизайн, искаме да изглежда така:
![default](https://cloud.githubusercontent.com/assets/16803986/12821643/e6ed81e4-cb6c-11e5-9c6b-f655d8953920.png)

Съответно като се попълни информацията значката се активира в Информация и в значки.
Когато качим снимка се появява и по средата.
По същата логика е с Име и Цел.

Значките са същите като от Значки :)

**Comment by bencheva-v** [comment]
Къде ще се качва тази снимка - за аватар и ако не е качена, какво да се показва?

**Comment by Meta-Luna** [comment]
Да се качва от компютъра на потребителя - той сам да си я избира от неговите файлове с бутон "качи аватар" от малкият прозорец за аватар ляво. 
Като не е качена нека излиза сив въпросителен, например:
![avatar](https://cloud.githubusercontent.com/assets/16803986/13146872/2c77a836-d660-11e5-9b91-e9a6cdc9a21f.png)

**Comment by bencheva-v** [comment]
Относно целта на потребителя, ще те помоля да я разпишеш в отделно issue  с повече подробности, а показването в профила е най-лесно, ще го добавим накрая. Неясното тук е дали потребителят ще си въвежда много цели или една, дали ще се показва само последната или всички и изобщо каква е цялата идея на тази цел. Нека е отделно, за да може да се разработи както трябва. Стефчо е говорил с Митко преди, когато е започната разработката и е предвидил цели на потребителите, но ни трябват пояснения, за да ги доразвием. Предвидени са в базата данни и за в момента има таблица Missions с полета id, Mission, AccomplishmentCriteria, BenefitCriteria, Inspiration. В това issue ще направя стилизирането на профила и промените, които искаш, като целта ще я направим отделно.

**Comment by Meta-Luna** [comment]
Ок, разбрах - супер :)
Утре ще се постарая да го направя.

2016-02-29 15:48 GMT+02:00 bencheva-v <notifications@github.com>:

> Относно целта на потребителя, ще те помоля да я разпишеш в отделно issue с
> повече подробности, а показването в профила е най-лесно, ще го добавим
> накрая. Неясното тук е дали потребителят ще си въвежда много цели или една,
> дали ще се показва само последната или всички и изобщо каква е цялата идея
> на тази цел. Нека е отделно, за да може да се разработи както трябва.
> Стефчо е говорил с Митко преди, когато е започната разработката и е
> предвидил цели на потребителите, но ни трябват пояснения, за да ги
> доразвием. Предвидени са в базата данни и за в момента има таблица Missions
> с полета id, Mission, AccomplishmentCriteria, BenefitCriteria, Inspiration.
> В това issue ще направя стилизирането на профила и промените, които искаш,
> като целта ще я направим отделно.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefanikolov/metareading/issues/24#issuecomment-190218203>
> .
>



-- 
~ ~ ~ ~ ~ ~ ~ ~~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
Александра Петрова
тел: 0890 110 494
адрес: ул. Прелом 8, София
www.pokajimi.com & www.metareading.com

**Comment by Meta-Luna** [comment]
За целта, май няма много скоро да го измъдрим :)

Може ли да помоля като качваме аватар да можем да го местим с мишката и да го позиционираме както ни харесва най-много. И да не се сменя резолюцията на картините, защотот в момента малко ги свива. 
Освен това, когато излеза от сайта и влезна отново аватара ми изчезва :/

И на мен нещо, не ми се оцветяват значките, където имам попълнена информация. 

*В задачката Профил->Значки съм обеснила подробно малко повече за точките, които носи всичко и натрупването + какви са значките за всяко нещо, защото настоящите в момента са доста детски.

![info](https://cloud.githubusercontent.com/assets/16803986/13601562/aa780e46-e539-11e5-8497-078c15e47ded.png)
