### ISSUE TITLE
Резултат - Скорост на четене

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#32]
Моля след като някой приключи скорост на четене и натисне стоп на Хронометъра, ниво 2 Възприемане да излиза на затъмнен фон с прозорец, който показва резултата от ниво Скорост

![result speed](https://cloud.githubusercontent.com/assets/16803986/13108915/baff3d9a-d57e-11e5-823f-e242d79e04e8.jpg)
Точките, който получава са 21.

**Comment by bencheva-v** [comment]
Тези прозорци ще е по-лесно да се направи да излизат при завършване на нивото и след като се кликне на бутона продължи да се отива на следващото ниво, като ще го направим да се клика само на него, а не на другите места из страницата.

**Comment by Meta-Luna** [comment]
Ок, да супер!
Просто като кликна бутона ме прехвърляше там, затова така го казвам :)
