### ISSUE TITLE
Памет

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#36]
Моля бутона старт да е зелен и да излиза отдясно.

Нека сменим 20-те думи със следните: комар вила писател грим пламък храм пижама роман лък обем концентрация ласо крокодил лазер фурма грация чип сатен хроника здрач

Добре ще е да има различни варианти думи, които да се редуват при повторно правене от един и същи човек. Възможно ли е и има ли как ние сами да добавяме следващите варианти?

Моля прозореца с резултата, които излиза да е следния:
![memory](https://cloud.githubusercontent.com/assets/16803986/13110615/d16d3f7c-d589-11e5-9b30-cf2f905d21e6.jpg)

**Comment by bencheva-v** [comment]
Ще променим в момента думите, които се показват, значките ще се променят ли? За да ги създавате вие, ще трябва да се допише тази функционалност. Може да се направят да показва произволно картинките, а може да се направи да се обвързват с конкретен номер 1,2,3,..., например слон, колело, жена да са като 1, меч, къща, вила - 2 и т.н. и да се въртят произволно тези групи думи.

**Comment by Meta-Luna** [comment]
Май най-оптимално ми звучи " слон, колело, жена да са като 1, меч, къща, вила - 2 и т.н." - за да стане така трябва да дам няколко варианта по 20 думи сега, нали така?

**Comment by bencheva-v** [comment]
да, добре е да имаме готови варианти, за да могат да се променят и да се направят да показва произволно по 1 вариант, а като минем спешните неща, ще ги направим и вие да ги добавяте.

**Comment by bencheva-v** [comment]
Ще те помоля да ми направиш няколко групи с думите, които ще се показват и баджовете им, може да ги направиш например в отделни папки с баджове и самата дума да е името на баджа за по-лесно. Все още не са променени думите, които се показват сега на сайта, защото не знам с какви значки да бъдат. Подготви ми най-напред тези, с които трябва да ги сменим, а след това вече и останалите. Освен това ми направи впечатление за точките, които се показват във блока "Чудесен резултат", че са по 21 - това точките, които се добавят към профила ли са, защото ако са те са правени по друг и мисля, че се добавят различен брой точки за всяко ниво по редицата на Фибоначи. Нека уточним дали всяко ниво дава по 21 точки или просто в текста да променим точките с тези, които се добавят в момента.

**Comment by Meta-Luna** [comment]
Да, точките са същите, които трябва да се добавят към профила. За тях съм обяснила, по колко дава всичко в issue - Значки :) 
Утре преди обед ще дам първите 20, а после и няколко варианта по 20 думи със значки, както ми обесни. 

Всичко е много яко, мерси за бързата реакция :)

**Comment by Meta-Luna** [comment]
Не знам как да кача папка тук, затова го прикачих в Подио - https://podio.com/metareadingcom/2-team/apps/backlog/items/401 :)

**Comment by bencheva-v** [comment]
Добавени са възможностите за качване от вас на картинки, дума и номер на пакет, в които ще са съответните картинки, като могат да се редактират и трият. Направено е произволното показване на пакет в нивото памет, като се вади на произволен принцип. За в момента са сложени двата пакета 1 и 2, който е прикачен в Подио. Всичките картинки могат да се видят на http://www.metareading.com/#!/level5, като съм добавила и линк в менюто на админа с име "Ниво Памет". Относно зеленият бутон да е вдясно ще застане в празното пространство в дясно, успоредно на знамената,  дали е удачно да е там? Ако да, ще го преместя не е проблем.

**Comment by Meta-Luna** [comment]
Права си и там си е добре. 
Исках да го преместим, защото е нужно да се скролне за да се натисне
