### ISSUE TITLE
План за SEO на сайта

### ISSUE THREAD

**Issue by batruji** [stefanikolov/metareading#4]
В момента голям проблем за сайта е, че нито една (поправи ме, ако греша) страница не се индексира правилно от google - crawler-a чете без включен JS, тоест не вижда нищо.

Как се подхожда при подобни проекти, за да има все пак индексиране - това е много важно за сайта. Какъв е планът ни в тази насока?

**Comment by stefanikolov** [comment]
Страниците са индексирани от 26.11.2015г. Ако искаш ми пиши да ти дам достъп до GWT за справки и планиране.
