### ISSUE TITLE
Липса на съдържание

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#41]
Хора :(
Много хора се оплакват, че в четвъртък и събота не са успявали да влезат почти никъде на сайта. Обесняват го по следният начин - влизам и не ми излиза нищо, освен няколко реда като код.

Това, което забелязвам е че главно проблема е на андроид. Ще кача няколко screenshot-a, за да видите за какво иде реч.

**Comment by Meta-Luna** [comment]
Като съм си в профила през Samsung Galaxy 5 Neo - няма проблем с Контакти, Цени, Кои сме ние, Кандидатствай

Пращам screenshot от 1. Интро курс и 2. Курсове (всички курсове)

**Comment by Meta-Luna** [comment]
![12773009_1153248414698862_529589318_o](https://cloud.githubusercontent.com/assets/16803986/13404480/68808602-df22-11e5-924f-77825662ae26.jpg)
![12788752_1153248444698859_285689572_o](https://cloud.githubusercontent.com/assets/16803986/13404481/6881da20-df22-11e5-9d12-9e319b147f1d.jpg)

**Comment by bencheva-v** [comment]
Оправено е и си работят нормално събитията.
