### ISSUE TITLE
Резултати

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#43]
В момента всеки, които влезе в резултати може да отвори профила на различните хора и да види всичките им лични данни. 
Много  е важно тези данни да са достъпни само за администраторски акаунти!

**Comment by stefanikolov** [comment]
Кои данни са публични и кои видими само от администратор? Цялата страница ли да скрием или определени полета?

**Comment by Meta-Luna** [comment]
Публични да са: име, фамили, град и аватар

**Comment by bencheva-v** [comment]
Оставени са да са публични само име, фамилия, град и аватар. Когато се достъпи профилът на друг потребител, изгледът е друг. Прегледай го как е в момента и ми разпиши issue за дизайна как да изглежда, защото мисля, че може да е много по-красиво от сега. Линковете към страниците са http://www.metareading.com/#!/admin/users/id_user, на мястото на id_user се пише id-то на потребителя, например, http://www.metareading.com/#!/admin/users/10 това е достъпът до моя профил.

**Comment by Meta-Luna** [comment]
Супер, ами относно дизайна в профила ми е много важно това issue - https://github.com/stefanikolov/metareading/issues/20 

Пък това ще го разпиша малко по нататък :)
