### ISSUE TITLE
Потвърждение запазено място

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#45]
Хората се регистрират по няколко пъти за събитие, защото не разбират че са направили нещо. Затова е важно след като натиснат бутона "Запази" да им излиза Pop up.
Най-отдолу на pop up-a е добре да има fb share бутон, като се share-ва пост със събитието - заглавието на поста е името на събитието, а описанието на поста е краткото описание.

Това важи  за всяко събитие от тип: курс, интро курс или клуб и има билети.

![fb share](https://cloud.githubusercontent.com/assets/16803986/13608304/debef624-e55c-11e5-8c00-b6db813dd378.png)
![thank you](https://cloud.githubusercontent.com/assets/16803986/13608306/dec0f492-e55c-11e5-9378-b8a2a5fae294.png)
![zapazi si mqsto](https://cloud.githubusercontent.com/assets/16803986/13608305/dec0b0ea-e55c-11e5-8d7a-cd1af5093f90.png)

Объркала съм мейла, съответно е ask@metareading.com 

Обвързано е с: https://github.com/stefanikolov/metareading/issues/39 
Относно фейсбук share-a: https://github.com/stefanikolov/metareading/issues/42

**Comment by bencheva-v** [comment]
Поп-ъпът е направен, стилизиран е, като единствено не е добавен бутонът за споделяне, защото има проблем с него и е отделен в отделно issue #54

**Comment by Meta-Luna** [comment]
Ок, супер :)
