### ISSUE TITLE
Клубове

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#46]
В меню Събития -> Клубове, моля най-скоро предстоящите събития да излизат най-отгоре, а тези на които не е отбелязана дата да излизат най-отдолу.

Към страницата добавяме 2 неща - общ календар на клубните срещи за годината + кратко обеснение какво е клуб. 

![club view](https://cloud.githubusercontent.com/assets/16803986/14760760/eee75e26-0954-11e6-80dd-03a2fef50096.png)

Само моля в текста да се редактира първото изречение: Клубните срещи са **4 етап** на прогрес в Метарийдинг.

**Comment by Meta-Luna** [comment]
Изпращам календара като изображения:
![mart](https://cloud.githubusercontent.com/assets/16803986/14760774/4ad8efa6-0955-11e6-9d88-8d60364b73c8.png)
![Uploading АВГУСТ.png…]()
![Uploading април.png…]()
![Uploading декември.png…]()
![Uploading май.png…]()
![Uploading ноември.png…]()
![Uploading октомври.png…]()
![Uploading септември.png…]()
![Uploading февруари.png…]()
![Uploading юли.png…]()
![Uploading юни.png…]()
![Uploading януари.png…]()

**Comment by Meta-Luna** [comment]
Още е съм направила всички събития за годината, а искам като се кликне на месец от календара да води направо към събитието. 
Има ли как сама да сложа линковете после или просто да ги дам тук като ги направя?

**Comment by bencheva-v** [comment]
Ще ги направя по следния начин в календара - директно ще взема информацията от съответните събития и ще се показва като дата в календара - датата на събитието, баджа ще се взема отново от събитието и темата също, като по този начин като си добавиш новите събития, ще се появят автоматично в календара без да има нужда да се пише нещо допълнително. Ако случайно в месеците има повече от 1 клуб, ще трябва да променим логиката, но ако е само по 1 клуб, няма никакъв проблем. Реално, ако ще има по повече може да вземаме първия от тях  и да показва него., за да не се налага някакво допълнително писане. Също искам да пидал дали винаги август сте почивка?

**Comment by Meta-Luna** [comment]
Чудесно звучи :) Това значи ли, че след като месеца отмине ще се премахва и от календара автоматично? 

Засега ще има само по един клуб на месец, след време е възможно да има и по два, но едва ли ще е в скоро бъдеще.

Специално Клубни срещи не предвиждаме да правим август месец, но за всеки случай ще питам Митко.

**Comment by bencheva-v** [comment]
Ще го направя да проверява дали има събитие и ако няма, направо да слага почивка, така  няма да се ограничаваме с конкретен месец и ако има предвидено събитие да се показва то. Да след като отмине месеца ще ги премахва от календара. Ще го направя да гледа текуща дата и напред.

**Comment by bencheva-v** [comment]
В календара на събитията, за да проверява за пауза сме го направили по следния начин: приемаме винаги, че месецът има 30 дни, без значени кой е, използва се от банките като принцип. След това, ако примерно са повече от 30 дните и имаме събитие на 13,06 и 18,07 на принципа с 30тте дни ще сложи събитие за пауза автоматично, за да не се получава така съм му дописала още проверки дали вече има събитие в този месец и ако има, да не слага пауза събитието. Качени са всичките неща, изтествах го за пауза събитие, работи си. Така, че можеш спокойно да си въвеждаш останалите събития в календара. Датите варират от текущ месец до датата на последно въведеното събитие.

**Comment by Meta-Luna** [comment]
Ехееееееее, супер!
Почвам да ги въвеждам с удоволствие :)
