### ISSUE TITLE
Проблем с линк 

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#49]
В грабо офертата сме оставили лин за регистрация към събитие - http://www.metareading.com/#!/events/137

Няколко потребители звъннаха с един и същи проблем, че веднага след влизане на линка (без да имат направена регистрация на сайта) им изскачат йероглифи.
Изпратиха ни screen shot:
![site bug](https://cloud.githubusercontent.com/assets/16803986/13916585/27002fbe-ef64-11e5-9f8e-3e5751abec94.png)

Основно използваният браузър е Internet Explorer, след съвет от нас опитват с Google Chrome, но излизало същото.

**Comment by bencheva-v** [comment]
Оправено е, проблемът беше същият като от Липса на съдържание.
