### ISSUE TITLE
Лични консултации - смяна на локация

### ISSUE THREAD

**Issue by batruji** [stefanikolov/metareading#5]
http://www.metareading.com/#!/events/119 -  да се премести в падащото меню Курсове и да се премахне от Интервю

https://podio.com/metareadingcom/contacts/apps/backlog/items/326

Моля също така, когато се прави commit по дадена задача да се прави reference на съответното issue, за да има проследяване на процеса - тоест да е видимо къде какъв код е променен за да се случи даденото събитие.

**Comment by stefanikolov** [comment]
Оправено е чрез от мейл, сега видях че го има и тук. Пропуснал съм да го затворя с комита.
