### ISSUE TITLE
Не мога да си вляза в профила

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#50]
Натискам Влез, зарежда и ме оставя на абсолютно същата страница, без да влиза в профила ми. Пробвах с Chrome и Mozilla.

Докато зарежда:
![dokato zarejda](https://cloud.githubusercontent.com/assets/16803986/14246603/f315a388-fa70-11e5-83c9-d415ea7df376.png)

И ме връща така, като зареди:
![sled zarejdane](https://cloud.githubusercontent.com/assets/16803986/14246613/fdfd659c-fa70-11e5-9d6d-d5bc8edd3da8.png)

**Comment by Meta-Luna** [comment]
Бяхте ми казвали, че е грешно, но автоматично линка излиза така: http://www.metareading.com/signin/#!/ 

Когато махна #! при презареждане отново се появява.

Излиза и при първоначално влизане в сайта - http://www.metareading.com/#!/

Примерно при предстоящи събития - http://www.metareading.com/#!/events/list/upcoming
Ако махна #! и оставя http://www.metareading.com/events/list/upcoming излиза:
![cannot get](https://cloud.githubusercontent.com/assets/16803986/14246731/beabface-fa71-11e5-86d8-949cb6a7fcbe.png)

**Comment by bencheva-v** [comment]
Току що тествах с моя профил и си влязох без проблем. Пробвах с някакъв измислен и само ми презареди страницата и нищо, както го описваш. Възможно ли е да въвеждаш грешно нещо или да го няма този профил? Напиши ми с какъв мейл се опитваш да влезеш. А относно линка, така си е от преди. Не е от това проблемът.

**Comment by Meta-Luna** [comment]
alex@metareading.com

**Comment by Meta-Luna** [comment]
Запаметени са ми и в браузъра, преписах ги и не е от грешна буква/цифра

**Comment by bencheva-v** [comment]
Няма го този мейл в базата данни  и от там е проблемът. Деси имаше такъв проблем с това, че и се изтриваше акаунта. Обърни се към Стефчо за това.

**Comment by Meta-Luna** [comment]
Той няма ли да го види тук?

**Comment by stefanikolov** [comment]
Всичко виждам аз? :) 
Трила ли си събитие?

**Comment by stefanikolov** [comment]
Оправих нещата. Регистрирай се пак, моля.

**Comment by Meta-Luna** [comment]
Трия доста често :D 
Ще ми създава ли проблеми отново това?

**Comment by Meta-Luna** [comment]
Регистрирах се :)

**Comment by stefanikolov** [comment]
Готово
