### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#52]
**Цялостен изглед на страницата:**

![newhpm](https://cloud.githubusercontent.com/assets/16803986/14648921/5ebec2ec-066d-11e6-9f89-1eb18709bb79.png)

**Изглед на падащо меню:**

![newhpcm](https://cloud.githubusercontent.com/assets/16803986/14648960/985c5442-066d-11e6-9389-a7e7cd9a77d9.png)

**Легенда: **

Лого, Начало - водят към началната страница

Интро - води към сегашната страница "Интро курс"

За нас - води към сегашната страница "Кои сме ние?"

Курсове - остават следните и в следната поредност: Мога да чета!, Обичам да чета!, Родители: Метачетене ТИЙН, Метачетене, Метабизнес, Бизнес консултация

Календар - на мястото на събития, вътре са: Предстоящи събития, Интро курс, Курс, Клуб
*всички събития се подреждат по най-скорошното, най отгоре
*събития без дата, отиват най-отдолу
*отминали събития, отиват под събитията без дата

Ресурси (на mockup-а е За теб!, но нека се казва Ресурси) - Тестове, Блог, Резултати

Моят профил - прехвърля към вход/регистрация

**Линкове:**

като кликнем върху: Кои сме ние?, Защо го правим?, В какво вярваме? - ни води към страница Кои сме ние?

от Какви способности и умения усвоявате?, като кликнем върху "И още" - ни води към страница Интро курс

от 4 етапа на прогрес:
Интро -> страница Интро
Интервю -> Кандидатстване
Курс -> курс Метачетене
Клуб -> страница Клуб

бутон Резултати си води към Резултати
бутон Календар води към Предстоящи събития
бутон Ресурси води към Тестове

LinkedIn бутон - https://bg.linkedin.com/in/karamanchev
Facebook - https://www.facebook.com/MetaReading/
Twiter - https://twitter.com/metareading

**Допълнения:**

Facebook - Like page 
Нека е по абсолютно същият начин, както е в този сайт: www.pesh.bg

Нека менюто да седи най-отгоре като скролваме надолу, както е на този сайт: http://trainingacademy.bg/ 

**Пояснения:**

Кандидатстване ще се обедини с Интервю ( https://github.com/stefanikolov/metareading/issues/53 )

Страница Тестове - съдържа МайерсБригс и Търговска интелигентност ( https://github.com/stefanikolov/metareading/issues/55 ) 

Блог - ще се разпише в друга задача

За нас - ще се променя и ще се разпише в друга задача

**Въпроси:**

Числата най-отгоре ще се променят всеки месец. Но искаме да са на същият фон като картината. Как е най-добре да се направят?

Текста "Бъди чат от..." искаме да излиза четливо на мобилка и също да е на същият фон като картината. Как е най-добре да се направи?

Заглавията: "Какви способности.." и "4 етапа.." също е важно да са четливи на мобилка. В този случай, по добре ли е да са извън фоновото изображение?

**Comment by Meta-Luna** [comment]
Прикачам нужните значки:
(смених тези на курс и клуб)

![6](https://cloud.githubusercontent.com/assets/16803986/14650454/833e79e4-0674-11e6-8cba-ba15252b0279.png)
![52](https://cloud.githubusercontent.com/assets/16803986/14650474/9df60626-0674-11e6-9efa-c11b879d179b.png)
![2345](https://cloud.githubusercontent.com/assets/16803986/14650483/a3f5888a-0674-11e6-8a7f-b135dc502877.png)
![59](https://cloud.githubusercontent.com/assets/16803986/14650514/bc124d04-0674-11e6-9b72-8fcd6b55b7f7.png)
![4](https://cloud.githubusercontent.com/assets/16803986/14650512/bc10f92c-0674-11e6-9601-3fae8afcb576.png)
![12](https://cloud.githubusercontent.com/assets/16803986/14650513/bc1133f6-0674-11e6-8e9f-5197198c75a2.png)
![33](https://cloud.githubusercontent.com/assets/16803986/14650532/d69241f2-0674-11e6-95f3-94e460e2487b.png)
![17](https://cloud.githubusercontent.com/assets/16803986/14650531/d6453600-0674-11e6-9362-7c8e0e2ea653.png)
![2 -interview](https://cloud.githubusercontent.com/assets/16803986/14650549/ebb4dc52-0674-11e6-9df4-e36a9eb2ea47.png)
![9 -games](https://cloud.githubusercontent.com/assets/16803986/14650560/f3da21d0-0674-11e6-802c-e45df49246bd.png)
Курс:
![mmm2](https://cloud.githubusercontent.com/assets/16803986/14650580/0f3c96d8-0675-11e6-97a3-90e9e28184a9.png)
Клуб:
![mmm3](https://cloud.githubusercontent.com/assets/16803986/14650585/11fd7680-0675-11e6-8ee7-8c306cdd2f19.png)

**Comment by Meta-Luna** [comment]
Фонови изображения:

![path-through-the-meadow-beautiful-green-nature_1280x800](https://cloud.githubusercontent.com/assets/16803986/14650644/493985c6-0675-11e6-9f3a-80a3a6bd0e2e.jpg)

![beautiful-sunset-wallpaper-1](https://cloud.githubusercontent.com/assets/16803986/14650665/5c28f2a2-0675-11e6-8a74-df6942c389ca.jpg)

![7041377-lastest-wallpapers-widescreen](https://cloud.githubusercontent.com/assets/16803986/14650676/695dadbe-0675-11e6-94f9-980141618818.jpg)

**Comment by Meta-Luna** [comment]
Лога:

![bheader1](https://cloud.githubusercontent.com/assets/16803986/14650825/f35d0bb8-0675-11e6-9e5d-454331779499.png)
![logo_su](https://cloud.githubusercontent.com/assets/16803986/14650824/f35be90e-0675-11e6-887a-9080e50f6ee3.png)
![movebg](https://cloud.githubusercontent.com/assets/16803986/14650828/f3607afa-0675-11e6-80b3-2418b637b346.png)
![pokaji mi logo](https://cloud.githubusercontent.com/assets/16803986/14650826/f35dd048-0675-11e6-8630-3b459bce1249.jpg)
![reading](https://cloud.githubusercontent.com/assets/16803986/14650827/f35e264c-0675-11e6-9806-8f3c5133b312.png)
![sis](https://cloud.githubusercontent.com/assets/16803986/14650829/f379e0da-0675-11e6-9843-b288feca8520.png)
![softuni-logo-flat_square-blue-300x235](https://cloud.githubusercontent.com/assets/16803986/14650830/f3c59976-0675-11e6-8a69-5a395d28cbf3.png)

Като кликнем на логата:
Movebg - http://movebg.com/2014/bg/
СУ - https://www.uni-sofia.bg/
StartItSmart - http://www.startitsmart.com/bg/
SoftUni - https://softuni.bg/
Фондацията - http://suggestology.org/
ПокажиМи - http://pokajimi.com/

**Comment by Meta-Luna** [comment]
Когато потребител влезе в профила си, бутона Моят профил се променя на Здравей Име + аватар

![profile](https://cloud.githubusercontent.com/assets/16803986/14651139/54284a6a-0677-11e6-88cb-b78c313d3738.png)

От там се появява падащо меню:
Моят профил и Излез

**Comment by bencheva-v** [comment]
За английската версия какви ще са текстовете ?

**Comment by Meta-Luna** [comment]
Все още не сме ги написали, но ще ги изпратим скоро

**Comment by bencheva-v** [comment]
Направена е началната страница за български език. Остава да се направи менюто. Страницата с тестовете е направена като article и може да се редактира директно от вас. Ще я достилизираме, за да изглежда по-добре, ако имате идеи даже как да изглежда ми разпиши. Ако ще се прави динамична тази страница да се разпише в отделно issue и също и за текстовете на английски.

**Comment by bencheva-v** [comment]
Направено е и менюто. Ще те помоля да го прегледаш и да ми пишеш дали е както трябва, за да знам, че е завършено. Относно:
"Календар - на мястото на събития, вътре са: Предстоящи събития, Интро курс, Курс, Клуб
*всички събития се подреждат по най-скорошното, най отгоре
*събития без дата, отиват най-отдолу
*отминали събития, отиват под събитията без дата" - в момента не са ли подредени по този начин ? Прегледай ги и пиши дали е нужно да правим промени по подреждането.

**Comment by Meta-Luna** [comment]
Сега ще ги прегледам, супер е станало :)

Но съм много зле... забравила съм страница Контакти. Може ли ад я добавим в навигацията.

**Comment by Meta-Luna** [comment]
Изображението не ми излиза центрирано:
![home](https://cloud.githubusercontent.com/assets/16803986/14851063/12e6a2c6-0c86-11e6-9281-99308baa7398.png)

Може ли другите 3 прозореца да ги изравним с първия:
![home 2](https://cloud.githubusercontent.com/assets/16803986/14851073/202841a6-0c86-11e6-8138-6e80c3fc5523.png)

Има ли как да направим тези 3 прозореца по-тесни и отстрани да оставим сребрист фон, както е на горният скрийншот спо-късите прозорци.
![home 3](https://cloud.githubusercontent.com/assets/16803986/14851107/66a11b4e-0c86-11e6-9c40-721f929be01a.png)

**Comment by Meta-Luna** [comment]
Относно падащото меню **Курс** да съдържа само предстоящи събития от тип Курс.
Всичко друго е супер. 

Задачи към другите страници:
Относно **Тестове** - https://github.com/stefanikolov/metareading/issues/55 
Относно **Кандидатстване** - https://github.com/stefanikolov/metareading/issues/53 
Относно **Блог** - ще разпишем допълнително

**Comment by Meta-Luna** [comment]
И последно - нека направо премахнем прозореца с Brain'n'Business и запиши се за онлайн инро.
Менюто да е залепено за изображението на homepage-a и съдържанието на другите страници.

![home 4](https://cloud.githubusercontent.com/assets/16803986/14851302/9f674420-0c87-11e6-95c2-71af279736c4.png)

**Comment by bencheva-v** [comment]
Направих промените, погледни само това с менюто дали е ок така и "Относно падащото меню Курс да съдържа само предстоящи събития от тип Курс." те в момента съдържат предстоящите събития какво точно трябва да се промени?

**Comment by Meta-Luna** [comment]
Ами отгоре да го няма описанието за курс Метачетене. Да е както е в Предстоящи събития, но само с предстоящите курсове.

Да супер е с менюто. Само на Контакт, да добавим едно "и" :)

Всичко друго е прекрасно :)
