### ISSUE TITLE
Кандидатствай

### ISSUE THREAD

**Issue by Meta-Luna** [stefanikolov/metareading#53]
Обединяваме Кандидатствай и Интервю

![default](https://cloud.githubusercontent.com/assets/16803986/14651714/c8c0c422-0679-11e6-981f-9284069d26d5.png)

Като в текста Интро курс и онлайн имат хиперлинк водещ към онлайн Интро курс

Може ли и текста най-отгоре със значката да е в отделен прозорец.

А текста "Подробности можете да намерите тук" да е заглавие, като "Кандидатствай" отдолу

Отдолу в кандидатствай остават в следният ред:
Мога да чета
Обичам да чета
Родители
Метачетене ТИЙН
Метачетене
Метабизнес
Бизнес консултация

Моля само горе да са 4 - Мета Тийн, Метачетене, Метабизнес и Бизнес консултация 
а от долу 3 - Мога, Обичам, Родители #

**Comment by Meta-Luna** [comment]
Нещо подобно:
![home5](https://cloud.githubusercontent.com/assets/16803986/14851501/07a0e23e-0c89-11e6-8e6e-dbdc3e1c7650.png)

Да ги вкараме направо в менюто горе.

**Comment by bencheva-v** [comment]
Направила съм информацията да се показва, когато потребителят се е логнал, ние правихме специално как да изглежда, когато не е логна, но трябва ли и допълнителната информация да се показва или всичко е направено както трябва?
