### ISSUE TITLE
Кандидатствай - промени

### ISSUE THREAD

**Issue by batruji** [stefanikolov/metareading#8]
1. Кандидатствай - да се премести като главен елемент в менюто, а не като под-меню

2. Pop up-а да не излиза като влезем в Кандидатствай от менюто, а да излиза на края на попълнен Интро курс. Както е описано в задачата за fb share: https://podio.com/metareadingcom/contacts/apps/backlog/items/273

3. Да няма drop down, а да излизат значки със съответните видове курсове (т.е. Метачетене,Метабизнес, Обичам да чета – а не Предстоящи събития) и като избереш, за кой курс кандидатстваш, значката да се оцветява.

4. Да се остави само поле с дата и час за интервю, което да се избира от потребителя, а отгоре да има текст, който гласи, че правим интервюта между 14:00 и 19:00ч. и след като изберет удобна дата и час ще получат потвърждение по мейл или телефон, че интервюто им е окончателно записано.
От там следва ние да получаваме автоматичен мейл, че някои е записал час за интервю и да го потвърждаваме.
 
текст: 
Можете да запишете удобни за вас час и дата за провеждане на индивидуално интервю. 
Интервюта провеждаме от понеделник до петък между 13:00ч. и 19:00ч.
Моля изчакайте потвърждение по телефон или мейл от нас. 
Ако не получите потвърждение в рамките на 24 часа, моля свържете се с нас.
Благодарим ви!

И ако може отстрани да сложим значка:
![333 cust](https://cloud.githubusercontent.com/assets/846646/11979619/80e4db9a-a99d-11e5-8878-cac8eeca3544.png)

 

 

(изготвяне на списък с периодично проверяващи  се неща за потвърждаване от администратори - следене за интервюта, регистрации за курсове..)

**Comment by bencheva-v** [comment]
Да няма drop down, а да излизат значки със съответните видове курсове (т.е. Метачетене,Метабизнес, Обичам да чета – а не Предстоящи събития) и като избереш, за кой курс кандидатстваш, значката да се оцветява. - идеята е да се сложат видовете курсове с техните значки, т.е.:
Мога да чета!
Обичам да чета!
Летни Нещотърсачи
Метачетене Тийн
Метачетене
Родители
Метабизнес
Творчески занимания за деца,
както са в менюто в момента, нали ?
Не знам само за "Индивидуални бизнес консултации" трябва ли да го има като вид курс?

**Comment by Meta-Luna** [comment]
Да моля, нека и Индивидуалната консултация да я има като вид курс.
Само искам да помоля - защото е свързано отново с нея, ако може да я прекръстим само на "Бизнес консултация" за да заема един ред и ако може и на нея да и добавим значка: 
![recency](https://cloud.githubusercontent.com/assets/16803986/12515219/f52d8912-c12f-11e5-8ebe-8c137584cedd.png) 

Ако може и Творчески занимания за деца да е на един ред със значката :)
Вариант да го прекръстим, за да е малко по-кратно е Творчески занимания-деца.

Извинявам се, че чак сега отговарям. Ще се поровя из github сега и предполагам от тук насам всички задачки тук да слагаме, така ли? :)

Весел уикенд!
